name: CI Pipeline

on:
  push:
    branches: ['**']

jobs:
  push-checks:
    name: Lint + SCA + Code Coverage + Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create Report Folder
        run: |
          mkdir -p report

      - name: Run pylint
        run: |
          pylint --ignore=tests app > report/pylint-report.txt

      - name: Run pip-audit (SCA)
        if: always()
        run: |
          pip-audit > report/pip-audit-report.txt

      - name: Run coverage (Code coverage) and unit test
        if: always()
        run: |
          coverage run -m pytest > report/coverage-report.txt
          coverage report --fail-under=70 >> report/coverage-report.txt
      
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: report/